<a href="https://colab.research.google.com/github/Elwing-Chou/tibame20260427/blob/main/tibame20260518.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import json
import os
import urllib.request as req
import pandas as pd

def get_danmu(sn, dn, chapter=-1):
    if not os.path.exists(dn):
        os.makedirs(dn)
    # list + dict: JSON格式
    url = f"https://api.gamer.com.tw/anime/v1/danmu.php?videoSn={sn}&geo=TW%2CHK"
    print("下載:", url)
    f = req.urlopen(url)
    content = f.read()
    content = json.loads(content)
    danmus = content["data"]["danmu"]

    df = pd.DataFrame(danmus)
    df["ch"] = chapter
    df.to_csv(f"{dn}/{sn}.csv", encoding="utf-8")
    return df

get_danmu("47221", "baha/芙莉蓮", 30)

下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47221&geo=TW%2CHK

,text,color,size,position,time,sn,userid,ch
0,讚阿XD,#FFFFFF,1,0,0,47806325,j11161984,30
1,悲報，距離完結還有9集,#FDE53D,1,0,0,47808838,BENNY319,30
2,巴哈我大哥,#FFFFFF,1,0,0,47812257,milk2009,30
3,簽 hiro,#0036FA,1,2,0,47840473,andyhiro,30
4,2026/01/22 簽~,#00C3FC,1,0,0,47866460,joe871114,30
...,...,...,...,...,...,...,...,...
2996,現實是會沖倒暗河而沿水脈而歸,#FFFFFF,1,0,14400,47828222,z999999op,30
2997,超級帥的大叔,#FFFFFF,1,0,14400,47835270,Jacschnapps,30
2998,2026.1.21 *,#FFFFFF,1,0,14400,47856058,s935602,30
2999,天啊！！！下一集就是南之勇者啦！！！,#FFFFFF,1,0,14400,47858790,khst9021735,30
3000,天啊 片尾好美,#FFFFFF,1,0,14400,48334763,kou050198,30

In [ ]:
# if 妳要下載整個資料夾
!zip -r /content/danmu.zip /content/baha

  adding: content/baha/ (stored 0%)
  adding: content/baha/芙莉蓮/ (stored 0%)
  adding: content/baha/芙莉蓮/47221.csv (deflated 56%)

In [ ]:
# if 妳要直接存google drive
# get_danmu("47221", "/content/drive/MyDrive/芙莉蓮")

In [19]:
import urllib.request as req
# Beautifulsoup4
import bs4 as bs

# url = "https://ani.gamer.com.tw/animeVideo.php?sn=47221"
# 因為colab, 動畫風會封鎖海外ip
url = "https://github.com/Elwing-Chou/tibame20260427/raw/refs/heads/main/%E8%8A%99%E8%8E%89%E8%93%AE.html"

h = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0"
}
r = req.Request(url, headers=h)
resp = req.urlopen(r)
content = resp.read()

dn = "baha/芙莉蓮"
# 這裡的動作就跟上面的json.loads依樣 是bytes型態轉換成bs裡自定義區塊型態
html = bs.BeautifulSoup(content)
# 區塊: find/find_all(html名字, 篩選條件)
for a in html.find_all("a"):
    # 當你拿到妳需要的區塊時候, 屬性: [屬性名稱]  文字: .get_text()
    a_href = a["href"]
    a_text = a.get_text()
    if a_href.startswith("?sn"):
        print(a_text, a_href)
        sn = a_href.split("=")[1]
        get_danmu(sn, dn, a_text)

29 ?sn=47221
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47221&geo=TW%2CHK
30 ?sn=47428
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47428&geo=TW%2CHK
31 ?sn=47429
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47429&geo=TW%2CHK
32 ?sn=47430
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47430&geo=TW%2CHK
33 ?sn=47567
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47567&geo=TW%2CHK
34 ?sn=47737
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47737&geo=TW%2CHK
35 ?sn=47915
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47915&geo=TW%2CHK
36 ?sn=47916
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47916&geo=TW%2CHK
37 ?sn=48126
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=48126&geo=TW%2CHK
38 ?sn=48127
下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=48127&geo=TW%2CHK

In [13]:
# 行操作
df = get_danmu("47221", "baha/芙莉蓮", 29)
# 單行
df["text"]
# 多行
cols = ["text", "userid"]
df[cols]
# 增加新一行(同一個預設值)
df["new"] = 20
df

下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47221&geo=TW%2CHK

,text,color,size,position,time,sn,userid,new
0,讚阿XD,#FFFFFF,1,0,0,47806325,j11161984,20
1,悲報，距離完結還有9集,#FDE53D,1,0,0,47808838,BENNY319,20
2,巴哈我大哥,#FFFFFF,1,0,0,47812257,milk2009,20
3,簽 hiro,#0036FA,1,2,0,47840473,andyhiro,20
4,2026/01/22 簽~,#00C3FC,1,0,0,47866460,joe871114,20
...,...,...,...,...,...,...,...,...
2996,現實是會沖倒暗河而沿水脈而歸,#FFFFFF,1,0,14400,47828222,z999999op,20
2997,超級帥的大叔,#FFFFFF,1,0,14400,47835270,Jacschnapps,20
2998,2026.1.21 *,#FFFFFF,1,0,14400,47856058,s935602,20
2999,天啊！！！下一集就是南之勇者啦！！！,#FFFFFF,1,0,14400,47858790,khst9021735,20
3000,天啊 片尾好美,#FFFFFF,1,0,14400,48334763,kou050198,20

In [27]:
# pandas兩大操作
# 1. 過濾: df[帶入跟資料筆數依樣多的True/False] True:留下 False:刪去
# 2. 轉換:
df = get_danmu("47221", "baha/芙莉蓮", 29)
test_df = df.head(3)
fil = [True, False, True]
test_df[fil]

下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47221&geo=TW%2CHK

    text    color  size  position  time        sn     userid  ch
0   讚阿XD  #FFFFFF     1         0     0  47806325  j11161984  29
2  巴哈我大哥  #FFFFFF     1         0     0  47812257   milk2009  29

In [31]:
pd.read_csv("/content/baha/芙莉蓮/47221.csv", encoding="utf-8", index_col=0)

,text,color,size,position,time,sn,userid,ch
0,讚阿XD,#FFFFFF,1,0,0,47806325,j11161984,29
1,悲報，距離完結還有9集,#FDE53D,1,0,0,47808838,BENNY319,29
2,巴哈我大哥,#FFFFFF,1,0,0,47812257,milk2009,29
3,簽 hiro,#0036FA,1,2,0,47840473,andyhiro,29
4,2026/01/22 簽~,#00C3FC,1,0,0,47866460,joe871114,29
...,...,...,...,...,...,...,...,...
2996,現實是會沖倒暗河而沿水脈而歸,#FFFFFF,1,0,14400,47828222,z999999op,29
2997,超級帥的大叔,#FFFFFF,1,0,14400,47835270,Jacschnapps,29
2998,2026.1.21 *,#FFFFFF,1,0,14400,47856058,s935602,29
2999,天啊！！！下一集就是南之勇者啦！！！,#FFFFFF,1,0,14400,47858790,khst9021735,29
3000,天啊 片尾好美,#FFFFFF,1,0,14400,48334763,kou050198,29

In [45]:
import glob
import pandas as pd

total = []
for fn in glob.glob("baha/*/*.csv"):
    df = pd.read_csv(fn, encoding="utf-8", index_col=0)
    total.append(df)

df = pd.concat(total)
df = df.sort_values(by="ch")
df = df.reset_index(drop=True)
df

,text,color,size,position,time,sn,userid,ch
0,來看我阿婆了,#FF02D3,2,2,12,47806883,mikipoddy,29
1,簽到,#FFFFFF,1,0,11,47858066,ty6282004,29
2,簽 hiro,#0036FA,1,2,0,47840473,andyhiro,29
3,巴哈我大哥,#FFFFFF,1,0,0,47812257,milk2009,29
4,悲報，距離完結還有9集,#FDE53D,1,0,0,47808838,BENNY319,29
...,...,...,...,...,...,...,...,...
25299,第一季呼應,#FFFFFF,1,0,12827,48582732,lydia94225,38
25300,你好意思說www,#FFFFFF,1,0,12827,48585262,updp10547789,38
25301,不對，因該要嚴厲管阿嬤才對,#FFFFFF,1,0,12827,48631383,Ado102404,38
25302,2026/3/29 完結灑花,#FFFFFF,1,0,12734,48597306,andrew951413,38
25303,0408,#FFFFFF,1,0,12734,48718482,z09735421,38

In [ ]:
import os
dn = "baha/processed"
if not os.path.exists(dn):
    os.makedirs(dn)

# value_counts()/unique()
uids = df["userid"].unique()
for u in uids:
    # print(u)
    # !!! 過濾
    fil = df["userid"] == u
    fp = f"{dn}/{u}.csv"
    df[fil].to_csv(fp, encoding="utf-8")