<a href="https://colab.research.google.com/github/Elwing-Chou/tibame20260427/blob/main/tibame20260518.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import json
import os
import urllib.request as req
import pandas as pd

def get_danmu(sn, dn):
    if not os.path.exists(dn):
        os.makedirs(dn)
    # list + dict: JSON格式
    url = f"https://api.gamer.com.tw/anime/v1/danmu.php?videoSn={sn}&geo=TW%2CHK"
    print("下載:", url)
    f = req.urlopen(url)
    content = f.read()
    content = json.loads(content)
    danmus = content["data"]["danmu"]

    df = pd.DataFrame(danmus)
    df.to_csv(f"{dn}/{sn}.csv", encoding="utf-8")
    return df

get_danmu("47221", "baha/芙莉蓮")

下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47221&geo=TW%2CHK

,text,color,size,position,time,sn,userid
0,讚阿XD,#FFFFFF,1,0,0,47806325,j11161984
1,悲報，距離完結還有9集,#FDE53D,1,0,0,47808838,BENNY319
2,巴哈我大哥,#FFFFFF,1,0,0,47812257,milk2009
3,簽 hiro,#0036FA,1,2,0,47840473,andyhiro
4,2026/01/22 簽~,#00C3FC,1,0,0,47866460,joe871114
...,...,...,...,...,...,...,...
2996,現實是會沖倒暗河而沿水脈而歸,#FFFFFF,1,0,14400,47828222,z999999op
2997,超級帥的大叔,#FFFFFF,1,0,14400,47835270,Jacschnapps
2998,2026.1.21 *,#FFFFFF,1,0,14400,47856058,s935602
2999,天啊！！！下一集就是南之勇者啦！！！,#FFFFFF,1,0,14400,47858790,khst9021735
3000,天啊 片尾好美,#FFFFFF,1,0,14400,48334763,kou050198

In [ ]:
# if 妳要下載整個資料夾
!zip -r /content/danmu.zip /content/baha

  adding: content/baha/ (stored 0%)
  adding: content/baha/芙莉蓮/ (stored 0%)
  adding: content/baha/芙莉蓮/47221.csv (deflated 56%)

In [ ]:
# if 妳要直接存google drive
# get_danmu("47221", "/content/drive/MyDrive/芙莉蓮")

In [9]:
import urllib.request as req
# Beautifulsoup4
import bs4 as bs

# url = "https://ani.gamer.com.tw/animeVideo.php?sn=47221"
# 因為colab, 動畫風會封鎖海外ip
url = "https://github.com/Elwing-Chou/tibame20260427/raw/refs/heads/main/%E8%8A%99%E8%8E%89%E8%93%AE.html"

h = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0"
}
r = req.Request(url, headers=h)
resp = req.urlopen(r)
content = resp.read()
# 這裡的動作就跟上面的json.loads依樣 是bytes型態轉換成bs裡自定義區塊型態
html = bs.BeautifulSoup(content)
# 區塊: find/find_all(html名字, 篩選條件)
for a in html.find_all("a"):
    # 當你拿到妳需要的區塊時候, 屬性: [屬性名稱]  文字: .get_text()
    a_href = a["href"]
    a_text = a.get_text()
    if a_href.startswith("?sn"):
        print(a_text, a_href)

29 ?sn=47221
30 ?sn=47428
31 ?sn=47429
32 ?sn=47430
33 ?sn=47567
34 ?sn=47737
35 ?sn=47915
36 ?sn=47916
37 ?sn=48126
38 ?sn=48127

In [13]:
# 行操作
df = get_danmu("47221", "baha/芙莉蓮")
# 單行
df["text"]
# 多行
cols = ["text", "userid"]
df[cols]
# 增加新一行(同一個預設值)
df["new"] = 20
df

下載: https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=47221&geo=TW%2CHK

,text,color,size,position,time,sn,userid,new
0,讚阿XD,#FFFFFF,1,0,0,47806325,j11161984,20
1,悲報，距離完結還有9集,#FDE53D,1,0,0,47808838,BENNY319,20
2,巴哈我大哥,#FFFFFF,1,0,0,47812257,milk2009,20
3,簽 hiro,#0036FA,1,2,0,47840473,andyhiro,20
4,2026/01/22 簽~,#00C3FC,1,0,0,47866460,joe871114,20
...,...,...,...,...,...,...,...,...
2996,現實是會沖倒暗河而沿水脈而歸,#FFFFFF,1,0,14400,47828222,z999999op,20
2997,超級帥的大叔,#FFFFFF,1,0,14400,47835270,Jacschnapps,20
2998,2026.1.21 *,#FFFFFF,1,0,14400,47856058,s935602,20
2999,天啊！！！下一集就是南之勇者啦！！！,#FFFFFF,1,0,14400,47858790,khst9021735,20
3000,天啊 片尾好美,#FFFFFF,1,0,14400,48334763,kou050198,20